parameters:
    # Adds a fallback DATABASE_URL if the env var is not set.
    # This allows you to run cache:warmup even if your
    # environment variables are not available yet.
    # You should not need to change this value.
    env(DATABASE_URL): ''

doctrine:
    dbal:
        # configure these for your database server
        driver: 'pdo_pgsql'
        server_version: '11.2'
        charset: utf8
        default_table_options:
            charset: utf8
            collate: -

        url: '%env(resolve:DATABASE_URL)%'

        schema_filter: '~^(?!admin_matkas_childmatkas_seq)~'

        types:
            user_user_id: 'App\Model\User\Entity\User\IdType'
            user_user_email: 'App\Model\User\Entity\User\EmailType'
            user_user_role: 'App\Model\User\Entity\User\RoleType'

            mesto_okrug_id: 'App\Model\Mesto\Entity\Okrugs\IdType'
            mesto_okrug_oblast_id: 'App\Model\Mesto\Entity\Okrugs\Oblasts\IdType'
            mesto_okrug_oblast_raion_id: 'App\Model\Mesto\Entity\Okrugs\Oblasts\Raions\IdType'
            mesto_mestonomer_id: 'App\Model\Mesto\Entity\InfaMesto\IdType'

            admin_uchasties_group_id: 'App\Model\Adminka\Entity\Uchasties\Group\IdType'
            admin_uchasties_uchastie_id: 'App\Model\Adminka\Entity\Uchasties\Uchastie\IdType'
            admin_uchasties_uchastie_status: 'App\Model\Adminka\Entity\Uchasties\Uchastie\StatusType'
            admin_uchasties_uchastie_email: 'App\Model\Adminka\Entity\Uchasties\Uchastie\EmailType'
            adminka_uchasties_persona_id: 'App\Model\Adminka\Entity\Uchasties\Personas\IdType'

            admin_matkas_plemmatka_id: 'App\Model\Adminka\Entity\Matkas\PlemMatka\IdType'
            admin_matkas_plemmatka_status: 'App\Model\Adminka\Entity\Matkas\PlemMatka\StatusType'
            admin_matkas_plemmatka_department_id: 'App\Model\Adminka\Entity\Matkas\PlemMatka\Department\IdType'

            admin_mattest_plemtest_id: 'App\Model\Adminka\Entity\MatTests\PlemTest\IdType'
            admin_mattest_plemtest_status: 'App\Model\Adminka\Entity\MatTests\PlemTest\StatusType'

            adminka_matkas_role_permissions: 'App\Model\Adminka\Entity\Matkas\Role\PermissionsType'
            adminka_matkas_role_id: 'App\Model\Adminka\Entity\Matkas\Role\IdType'

            admin_matkas_kategoria_id: 'App\Model\Adminka\Entity\Matkas\Kategoria\IdType'
            admin_matkas_kategoria_permissions: 'App\Model\Adminka\Entity\Matkas\Kategoria\PermissionsType'

            admin_drevmatka_id: 'App\Model\Adminka\Entity\DrevMatkas\DrevMatka\IdType'
            admin_drevmatka_status: 'App\Model\Adminka\Entity\DrevMatkas\DrevMatka\StatusType'

            adm_drev_sezondrev_id: 'App\Model\Adminka\Entity\DrevMatkas\DrevMatka\SezonDrev\IdType'

            dre_stran_id: 'App\Model\Drevos\Entity\Strans\IdType'

            dre_ras_id: 'App\Model\Drevos\Entity\Rass\IdType'
            dre_ras_rod_id: 'App\Model\Drevos\Entity\Rass\Rods\IdType'
            dre_ras_rod_lini_id: 'App\Model\Drevos\Entity\Rass\Rods\Linis\IdType'
            dre_ras_rod_lini_wet_id: 'App\Model\Drevos\Entity\Rass\Rods\Linis\Wetkas\IdType'
            dre_ras_rod_lini_wet_nomw_id: 'App\Model\Drevos\Entity\Rass\Rods\Linis\Wetkas\NomWets\IdType'
            dre_ras_rod_lini_wet_nomw_trut_id: 'App\Model\Drevos\Entity\Rass\Rods\Linis\Wetkas\NomWets\MatTruts\IdType'
            dre_ras_rod_lini_wet_nomw_nom_stat: 'App\Model\Drevos\Entity\Rass\Rods\Linis\Wetkas\NomWets\MatTruts\Noms\StatuType'
            dre_ras_rod_lini_wet_nomw_nom_id: 'App\Model\Drevos\Entity\Rass\Rods\Linis\Wetkas\NomWets\MatTruts\Noms\IdType'

            adminka_rasa_id: 'App\Model\Adminka\Entity\Rasas\IdType'
            adminka_rasa_linia_id: 'App\Model\Adminka\Entity\Rasas\Linias\IdType'
            adminka_rasa_linia_nomer_status: 'App\Model\Adminka\Entity\Rasas\Linias\Nomers\StatusType'
            adminka_rasa_linia_nomer_id: 'App\Model\Adminka\Entity\Rasas\Linias\Nomers\IdType'

            adminka_otec_ras_id: 'App\Model\Adminka\Entity\OtecForRas\IdType'
            adminka_otec_ras_linia_id: 'App\Model\Adminka\Entity\OtecForRas\Linias\IdType'
            adminka_otec_ras_linia_nomer_id: 'App\Model\Adminka\Entity\OtecForRas\Linias\Nomers\IdType'

            admin_matkas_childmatka_id: 'App\Model\Adminka\Entity\Matkas\ChildMatka\IdType'
            admin_matkas_childmatka_type: 'App\Model\Adminka\Entity\Matkas\ChildMatka\TypeType'
            admin_matkas_childmatka_status: 'App\Model\Adminka\Entity\Matkas\ChildMatka\StatusType'

            admin_sezons_goda_id: 'App\Model\Adminka\Entity\Sezons\Godas\IdType'

            comment_comment_id: 'App\Model\Comment\Entity\Comment\IdType'
            comment_comment_author_id: 'App\Model\Comment\Entity\Comment\AuthorIdType'
            adminka_matkas_childmatka_file_id: 'App\Model\Adminka\Entity\Matkas\ChildMatka\File\IdType'
            admin_matkas_child_change_id: 'App\Model\Adminka\Entity\Matkas\ChildMatka\Change\IdType'


    orm:
        auto_generate_proxy_classes: true
        naming_strategy: doctrine.orm.naming_strategy.underscore
        auto_mapping: true
        mappings:
            User:
                is_bundle: false
                type: annotation
                dir: '%kernel.project_dir%/src/Model/User/Entity'
                prefix: 'App\Model\User\Entity'
                alias: User
            Mesto:
                is_bundle: false
                type: annotation
                dir: '%kernel.project_dir%/src/Model/Mesto/Entity'
                prefix: 'App\Model\Mesto\Entity'
                alias: Mesto
            Comment:
                is_bundle: false
                type: annotation
                dir: '%kernel.project_dir%/src/Model/Comment/Entity'
                prefix: 'App\Model\Comment\Entity'
                alias: User
            Adminka:
                is_bundle: false
                type: annotation
                dir: '%kernel.project_dir%/src/Model/Adminka/Entity'
                prefix: 'App\Model\Adminka\Entity'
                alias: Adminka

            Drevos:
                is_bundle: false
                type: annotation
                dir: '%kernel.project_dir%/src/Model/Drevos/Entity'
                prefix: 'App\Model\Drevos\Entity'
                alias: Drevos
   
